/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// A code representing the source of the flight availability
    /// </summary>
    /// <value>A code representing the source of the flight availability</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum AvailabilitySourceCodeENUM
    {
        
        /// <summary>
        /// Enum A for value: A
        /// </summary>
        [EnumMember(Value = "A")]
        A = 1,
        
        /// <summary>
        /// Enum B for value: B
        /// </summary>
        [EnumMember(Value = "B")]
        B = 2,
        
        /// <summary>
        /// Enum C for value: C
        /// </summary>
        [EnumMember(Value = "C")]
        C = 3,
        
        /// <summary>
        /// Enum D for value: D
        /// </summary>
        [EnumMember(Value = "D")]
        D = 4,
        
        /// <summary>
        /// Enum E for value: E
        /// </summary>
        [EnumMember(Value = "E")]
        E = 5,
        
        /// <summary>
        /// Enum F for value: F
        /// </summary>
        [EnumMember(Value = "F")]
        F = 6,
        
        /// <summary>
        /// Enum G for value: G
        /// </summary>
        [EnumMember(Value = "G")]
        G = 7,
        
        /// <summary>
        /// Enum H for value: H
        /// </summary>
        [EnumMember(Value = "H")]
        H = 8,
        
        /// <summary>
        /// Enum I for value: I
        /// </summary>
        [EnumMember(Value = "I")]
        I = 9,
        
        /// <summary>
        /// Enum J for value: J
        /// </summary>
        [EnumMember(Value = "J")]
        J = 10,
        
        /// <summary>
        /// Enum K for value: K
        /// </summary>
        [EnumMember(Value = "K")]
        K = 11,
        
        /// <summary>
        /// Enum L for value: L
        /// </summary>
        [EnumMember(Value = "L")]
        L = 12,
        
        /// <summary>
        /// Enum M for value: M
        /// </summary>
        [EnumMember(Value = "M")]
        M = 13,
        
        /// <summary>
        /// Enum N for value: N
        /// </summary>
        [EnumMember(Value = "N")]
        N = 14,
        
        /// <summary>
        /// Enum O for value: O
        /// </summary>
        [EnumMember(Value = "O")]
        O = 15,
        
        /// <summary>
        /// Enum P for value: P
        /// </summary>
        [EnumMember(Value = "P")]
        P = 16,
        
        /// <summary>
        /// Enum Q for value: Q
        /// </summary>
        [EnumMember(Value = "Q")]
        Q = 17,
        
        /// <summary>
        /// Enum S for value: S
        /// </summary>
        [EnumMember(Value = "S")]
        S = 18,
        
        /// <summary>
        /// Enum T for value: T
        /// </summary>
        [EnumMember(Value = "T")]
        T = 19,
        
        /// <summary>
        /// Enum U for value: U
        /// </summary>
        [EnumMember(Value = "U")]
        U = 20,
        
        /// <summary>
        /// Enum X for value: X
        /// </summary>
        [EnumMember(Value = "X")]
        X = 21,
        
        /// <summary>
        /// Enum Y for value: Y
        /// </summary>
        [EnumMember(Value = "Y")]
        Y = 22,
        
        /// <summary>
        /// Enum Z for value: Z
        /// </summary>
        [EnumMember(Value = "Z")]
        Z = 23
    }

}
