/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// BuildOptionsFromProducts
    /// </summary>
    [DataContract]
    public partial class BuildOptionsFromProducts : BuildOptions,  IEquatable<BuildOptionsFromProducts>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildOptionsFromProducts" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BuildOptionsFromProducts() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildOptionsFromProducts" /> class.
        /// </summary>
        /// <param name="buildFromProductsRequest">Assigned Type: ctlg-1100:BuildFromProductsRequest (required).</param>
        /// <param name="extensionPointChoice">extensionPointChoice.</param>
        public BuildOptionsFromProducts(BuildFromProductsRequest buildFromProductsRequest = default(BuildFromProductsRequest), ExtensionPointChoice extensionPointChoice = default(ExtensionPointChoice), string type = "BuildOptionsFromProducts", int? maxNumberOfUpsellsToReturn = default(int?), PaymentCriteria paymentCriteria = default(PaymentCriteria), FareRuleEnum? fareRuleType = default(FareRuleEnum?), List<FareRuleCategoryEnum> fareRuleCategory = default(List<FareRuleCategoryEnum>), bool? returnBrandedFaresInd = default(bool?), Object extensionPoint = default(Object)) : base(type, maxNumberOfUpsellsToReturn, paymentCriteria, fareRuleType, fareRuleCategory, returnBrandedFaresInd, extensionPoint)
        {
            // to ensure "buildFromProductsRequest" is required (not null)
            if (buildFromProductsRequest == null)
            {
                throw new InvalidDataException("buildFromProductsRequest is a required property for BuildOptionsFromProducts and cannot be null");
            }
            else
            {
                this.BuildFromProductsRequest = buildFromProductsRequest;
            }
            this.ExtensionPointChoice = extensionPointChoice;
        }
        
        /// <summary>
        /// Assigned Type: ctlg-1100:BuildFromProductsRequest
        /// </summary>
        /// <value>Assigned Type: ctlg-1100:BuildFromProductsRequest</value>
        [DataMember(Name="BuildFromProductsRequest", EmitDefaultValue=false)]
        public BuildFromProductsRequest BuildFromProductsRequest { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointChoice
        /// </summary>
        [DataMember(Name="ExtensionPoint_Choice", EmitDefaultValue=false)]
        public ExtensionPointChoice ExtensionPointChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BuildOptionsFromProducts {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  BuildFromProductsRequest: ").Append(BuildFromProductsRequest).Append("\n");
            sb.Append("  ExtensionPointChoice: ").Append(ExtensionPointChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BuildOptionsFromProducts);
        }

        /// <summary>
        /// Returns true if BuildOptionsFromProducts instances are equal
        /// </summary>
        /// <param name="input">Instance of BuildOptionsFromProducts to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BuildOptionsFromProducts input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.BuildFromProductsRequest == input.BuildFromProductsRequest ||
                    (this.BuildFromProductsRequest != null &&
                    this.BuildFromProductsRequest.Equals(input.BuildFromProductsRequest))
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointChoice == input.ExtensionPointChoice ||
                    (this.ExtensionPointChoice != null &&
                    this.ExtensionPointChoice.Equals(input.ExtensionPointChoice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.BuildFromProductsRequest != null)
                    hashCode = hashCode * 59 + this.BuildFromProductsRequest.GetHashCode();
                if (this.ExtensionPointChoice != null)
                    hashCode = hashCode * 59 + this.ExtensionPointChoice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
