/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// BuildFromOfferAir
    /// </summary>
    [DataContract]
    public partial class BuildFromOfferAir : BuildFromOffer,  IEquatable<BuildFromOfferAir>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildFromOfferAir" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected BuildFromOfferAir() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="BuildFromOfferAir" /> class.
        /// </summary>
        /// <param name="segmentSequence">The segmentSequence within the product the action is being requested for. Used when multiple in a product (required).</param>
        /// <param name="extensionPointChoice">extensionPointChoice.</param>
        public BuildFromOfferAir(List<int?> segmentSequence = default(List<int?>), ExtensionPointChoice extensionPointChoice = default(ExtensionPointChoice), string type = "BuildFromOfferAir", OfferIdentifier offerIdentifier = default(OfferIdentifier), List<ProductIdentifier> productIdentifier = default(List<ProductIdentifier>), Object extensionPoint = default(Object)) : base(type, offerIdentifier, productIdentifier, extensionPoint)
        {
            // to ensure "segmentSequence" is required (not null)
            if (segmentSequence == null)
            {
                throw new InvalidDataException("segmentSequence is a required property for BuildFromOfferAir and cannot be null");
            }
            else
            {
                this.SegmentSequence = segmentSequence;
            }
            this.ExtensionPointChoice = extensionPointChoice;
        }
        
        /// <summary>
        /// The segmentSequence within the product the action is being requested for. Used when multiple in a product
        /// </summary>
        /// <value>The segmentSequence within the product the action is being requested for. Used when multiple in a product</value>
        [DataMember(Name="SegmentSequence", EmitDefaultValue=false)]
        public List<int?> SegmentSequence { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointChoice
        /// </summary>
        [DataMember(Name="ExtensionPoint_Choice", EmitDefaultValue=false)]
        public ExtensionPointChoice ExtensionPointChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class BuildFromOfferAir {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  SegmentSequence: ").Append(SegmentSequence).Append("\n");
            sb.Append("  ExtensionPointChoice: ").Append(ExtensionPointChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as BuildFromOfferAir);
        }

        /// <summary>
        /// Returns true if BuildFromOfferAir instances are equal
        /// </summary>
        /// <param name="input">Instance of BuildFromOfferAir to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(BuildFromOfferAir input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.SegmentSequence == input.SegmentSequence ||
                    this.SegmentSequence != null &&
                    this.SegmentSequence.SequenceEqual(input.SegmentSequence)
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointChoice == input.ExtensionPointChoice ||
                    (this.ExtensionPointChoice != null &&
                    this.ExtensionPointChoice.Equals(input.ExtensionPointChoice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.SegmentSequence != null)
                    hashCode = hashCode * 59 + this.SegmentSequence.GetHashCode();
                if (this.ExtensionPointChoice != null)
                    hashCode = hashCode * 59 + this.ExtensionPointChoice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
