/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Specifies the cabin type (e.g. first, business, economy).
    /// </summary>
    /// <value>Specifies the cabin type (e.g. first, business, economy).</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CabinAirEnum
    {
        
        /// <summary>
        /// Enum PremiumFirst for value: PremiumFirst
        /// </summary>
        [EnumMember(Value = "PremiumFirst")]
        PremiumFirst = 1,
        
        /// <summary>
        /// Enum First for value: First
        /// </summary>
        [EnumMember(Value = "First")]
        First = 2,
        
        /// <summary>
        /// Enum Business for value: Business
        /// </summary>
        [EnumMember(Value = "Business")]
        Business = 3,
        
        /// <summary>
        /// Enum PremiumEconomy for value: PremiumEconomy
        /// </summary>
        [EnumMember(Value = "PremiumEconomy")]
        PremiumEconomy = 4,
        
        /// <summary>
        /// Enum Economy for value: Economy
        /// </summary>
        [EnumMember(Value = "Economy")]
        Economy = 5
    }

}
