/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CatalogProductOfferingSelection
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "@type")]
    public partial class CatalogProductOfferingSelection :  IEquatable<CatalogProductOfferingSelection>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogProductOfferingSelection" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected CatalogProductOfferingSelection() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogProductOfferingSelection" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="catalogProductOfferingIdentifier">Assigned Type: ctlg-1100:CatalogProductOffering_ID (required).</param>
        /// <param name="productBrandOfferingIdentifier">Assigned Type: c-1100:Identifier (required).</param>
        /// <param name="productIdentifier">productIdentifier.</param>
        /// <param name="segmentSequence">segmentSequence.</param>
        /// <param name="extensionPoint">extensionPoint.</param>
        public CatalogProductOfferingSelection(string type = default(string), CatalogProductOfferingIdentifier catalogProductOfferingIdentifier = default(CatalogProductOfferingIdentifier), Identifier productBrandOfferingIdentifier = default(Identifier), List<ProductIdentifier> productIdentifier = default(List<ProductIdentifier>), List<int?> segmentSequence = default(List<int?>), Object extensionPoint = default(Object))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for CatalogProductOfferingSelection and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            // to ensure "catalogProductOfferingIdentifier" is required (not null)
            if (catalogProductOfferingIdentifier == null)
            {
                throw new InvalidDataException("catalogProductOfferingIdentifier is a required property for CatalogProductOfferingSelection and cannot be null");
            }
            else
            {
                this.CatalogProductOfferingIdentifier = catalogProductOfferingIdentifier;
            }
            // to ensure "productBrandOfferingIdentifier" is required (not null)
            if (productBrandOfferingIdentifier == null)
            {
                throw new InvalidDataException("productBrandOfferingIdentifier is a required property for CatalogProductOfferingSelection and cannot be null");
            }
            else
            {
                this.ProductBrandOfferingIdentifier = productBrandOfferingIdentifier;
            }
            this.ProductIdentifier = productIdentifier;
            this.SegmentSequence = segmentSequence;
            this.ExtensionPoint = extensionPoint;
        }
        
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="@type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Assigned Type: ctlg-1100:CatalogProductOffering_ID
        /// </summary>
        /// <value>Assigned Type: ctlg-1100:CatalogProductOffering_ID</value>
        [DataMember(Name="CatalogProductOfferingIdentifier", EmitDefaultValue=false)]
        public CatalogProductOfferingIdentifier CatalogProductOfferingIdentifier { get; set; }

        /// <summary>
        /// Assigned Type: c-1100:Identifier
        /// </summary>
        /// <value>Assigned Type: c-1100:Identifier</value>
        [DataMember(Name="ProductBrandOfferingIdentifier", EmitDefaultValue=false)]
        public Identifier ProductBrandOfferingIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets ProductIdentifier
        /// </summary>
        [DataMember(Name="ProductIdentifier", EmitDefaultValue=false)]
        public List<ProductIdentifier> ProductIdentifier { get; set; }

        /// <summary>
        /// Gets or Sets SegmentSequence
        /// </summary>
        [DataMember(Name="SegmentSequence", EmitDefaultValue=false)]
        public List<int?> SegmentSequence { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPoint
        /// </summary>
        [DataMember(Name="ExtensionPoint", EmitDefaultValue=false)]
        public Object ExtensionPoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CatalogProductOfferingSelection {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  CatalogProductOfferingIdentifier: ").Append(CatalogProductOfferingIdentifier).Append("\n");
            sb.Append("  ProductBrandOfferingIdentifier: ").Append(ProductBrandOfferingIdentifier).Append("\n");
            sb.Append("  ProductIdentifier: ").Append(ProductIdentifier).Append("\n");
            sb.Append("  SegmentSequence: ").Append(SegmentSequence).Append("\n");
            sb.Append("  ExtensionPoint: ").Append(ExtensionPoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CatalogProductOfferingSelection);
        }

        /// <summary>
        /// Returns true if CatalogProductOfferingSelection instances are equal
        /// </summary>
        /// <param name="input">Instance of CatalogProductOfferingSelection to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CatalogProductOfferingSelection input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.CatalogProductOfferingIdentifier == input.CatalogProductOfferingIdentifier ||
                    (this.CatalogProductOfferingIdentifier != null &&
                    this.CatalogProductOfferingIdentifier.Equals(input.CatalogProductOfferingIdentifier))
                ) && 
                (
                    this.ProductBrandOfferingIdentifier == input.ProductBrandOfferingIdentifier ||
                    (this.ProductBrandOfferingIdentifier != null &&
                    this.ProductBrandOfferingIdentifier.Equals(input.ProductBrandOfferingIdentifier))
                ) && 
                (
                    this.ProductIdentifier == input.ProductIdentifier ||
                    this.ProductIdentifier != null &&
                    this.ProductIdentifier.SequenceEqual(input.ProductIdentifier)
                ) && 
                (
                    this.SegmentSequence == input.SegmentSequence ||
                    this.SegmentSequence != null &&
                    this.SegmentSequence.SequenceEqual(input.SegmentSequence)
                ) && 
                (
                    this.ExtensionPoint == input.ExtensionPoint ||
                    (this.ExtensionPoint != null &&
                    this.ExtensionPoint.Equals(input.ExtensionPoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.CatalogProductOfferingIdentifier != null)
                    hashCode = hashCode * 59 + this.CatalogProductOfferingIdentifier.GetHashCode();
                if (this.ProductBrandOfferingIdentifier != null)
                    hashCode = hashCode * 59 + this.ProductBrandOfferingIdentifier.GetHashCode();
                if (this.ProductIdentifier != null)
                    hashCode = hashCode * 59 + this.ProductIdentifier.GetHashCode();
                if (this.SegmentSequence != null)
                    hashCode = hashCode * 59 + this.SegmentSequence.GetHashCode();
                if (this.ExtensionPoint != null)
                    hashCode = hashCode * 59 + this.ExtensionPoint.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
