/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CatalogProductOfferingsQueryRequestWrapper
    /// </summary>
    [DataContract]
    public partial class CatalogProductOfferingsQueryRequestWrapper :  IEquatable<CatalogProductOfferingsQueryRequestWrapper>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogProductOfferingsQueryRequestWrapper" /> class.
        /// </summary>
        /// <param name="catalogProductOfferingsQueryRequest">catalogProductOfferingsQueryRequest.</param>
        public CatalogProductOfferingsQueryRequestWrapper(CatalogProductOfferingsQueryRequest catalogProductOfferingsQueryRequest = default(CatalogProductOfferingsQueryRequest))
        {
            this.CatalogProductOfferingsQueryRequest = catalogProductOfferingsQueryRequest;
        }
        
        /// <summary>
        /// Gets or Sets CatalogProductOfferingsQueryRequest
        /// </summary>
        [DataMember(Name="CatalogProductOfferingsQueryRequest", EmitDefaultValue=false)]
        public CatalogProductOfferingsQueryRequest CatalogProductOfferingsQueryRequest { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CatalogProductOfferingsQueryRequestWrapper {\n");
            sb.Append("  CatalogProductOfferingsQueryRequest: ").Append(CatalogProductOfferingsQueryRequest).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CatalogProductOfferingsQueryRequestWrapper);
        }

        /// <summary>
        /// Returns true if CatalogProductOfferingsQueryRequestWrapper instances are equal
        /// </summary>
        /// <param name="input">Instance of CatalogProductOfferingsQueryRequestWrapper to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CatalogProductOfferingsQueryRequestWrapper input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CatalogProductOfferingsQueryRequest == input.CatalogProductOfferingsQueryRequest ||
                    (this.CatalogProductOfferingsQueryRequest != null &&
                    this.CatalogProductOfferingsQueryRequest.Equals(input.CatalogProductOfferingsQueryRequest))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CatalogProductOfferingsQueryRequest != null)
                    hashCode = hashCode * 59 + this.CatalogProductOfferingsQueryRequest.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
