/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// CatalogProductOfferingsResponseWrapper
    /// </summary>
    [DataContract]
    public partial class CatalogProductOfferingsResponseWrapper :  IEquatable<CatalogProductOfferingsResponseWrapper>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="CatalogProductOfferingsResponseWrapper" /> class.
        /// </summary>
        /// <param name="catalogProductOfferingsResponse">catalogProductOfferingsResponse.</param>
        public CatalogProductOfferingsResponseWrapper(CatalogProductOfferingsResponse catalogProductOfferingsResponse = default(CatalogProductOfferingsResponse))
        {
            this.CatalogProductOfferingsResponse = catalogProductOfferingsResponse;
        }
        
        /// <summary>
        /// Gets or Sets CatalogProductOfferingsResponse
        /// </summary>
        [DataMember(Name="CatalogProductOfferingsResponse", EmitDefaultValue=false)]
        public CatalogProductOfferingsResponse CatalogProductOfferingsResponse { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class CatalogProductOfferingsResponseWrapper {\n");
            sb.Append("  CatalogProductOfferingsResponse: ").Append(CatalogProductOfferingsResponse).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as CatalogProductOfferingsResponseWrapper);
        }

        /// <summary>
        /// Returns true if CatalogProductOfferingsResponseWrapper instances are equal
        /// </summary>
        /// <param name="input">Instance of CatalogProductOfferingsResponseWrapper to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(CatalogProductOfferingsResponseWrapper input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CatalogProductOfferingsResponse == input.CatalogProductOfferingsResponse ||
                    (this.CatalogProductOfferingsResponse != null &&
                    this.CatalogProductOfferingsResponse.Equals(input.CatalogProductOfferingsResponse))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CatalogProductOfferingsResponse != null)
                    hashCode = hashCode * 59 + this.CatalogProductOfferingsResponse.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
