/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Type of commission
    /// </summary>
    /// <value>Type of commission</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum CommissionEnum
    {
        
        /// <summary>
        /// Enum Full for value: Full
        /// </summary>
        [EnumMember(Value = "Full")]
        Full = 1,
        
        /// <summary>
        /// Enum Partial for value: Partial
        /// </summary>
        [EnumMember(Value = "Partial")]
        Partial = 2,
        
        /// <summary>
        /// Enum NonPaying for value: Non-paying
        /// </summary>
        [EnumMember(Value = "Non-paying")]
        NonPaying = 3,
        
        /// <summary>
        /// Enum NoShow for value: No-show
        /// </summary>
        [EnumMember(Value = "No-show")]
        NoShow = 4,
        
        /// <summary>
        /// Enum Adjustment for value: Adjustment
        /// </summary>
        [EnumMember(Value = "Adjustment")]
        Adjustment = 5,
        
        /// <summary>
        /// Enum Commissionable for value: Commissionable
        /// </summary>
        [EnumMember(Value = "Commissionable")]
        Commissionable = 6
    }

}
