/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// The source of the content to be returned in CatalogOfferings
    /// </summary>
    /// <value>The source of the content to be returned in CatalogOfferings</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum ContentSourceEnum
    {
        
        /// <summary>
        /// Enum GDS for value: GDS
        /// </summary>
        [EnumMember(Value = "GDS")]
        GDS = 1,
        
        /// <summary>
        /// Enum NDC for value: NDC
        /// </summary>
        [EnumMember(Value = "NDC")]
        NDC = 2
    }

}
