/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines the type of fares to return (Only public fares, Only private fares, Only agency private fares, Only\\nDefines the type of fares to return
    /// </summary>
    /// <value>Defines the type of fares to return (Only public fares, Only private fares, Only agency private fares, Only\\nDefines the type of fares to return</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FareTypeEnum
    {
        
        /// <summary>
        /// Enum PublicFare for value: PublicFare
        /// </summary>
        [EnumMember(Value = "PublicFare")]
        PublicFare = 1,
        
        /// <summary>
        /// Enum AgencyPrivateFare for value: AgencyPrivateFare
        /// </summary>
        [EnumMember(Value = "AgencyPrivateFare")]
        AgencyPrivateFare = 2,
        
        /// <summary>
        /// Enum AirlinePrivateFare for value: AirlinePrivateFare
        /// </summary>
        [EnumMember(Value = "AirlinePrivateFare")]
        AirlinePrivateFare = 3,
        
        /// <summary>
        /// Enum NetFare for value: NetFare
        /// </summary>
        [EnumMember(Value = "NetFare")]
        NetFare = 4
    }

}
