/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines FrequencyEnum
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum FrequencyEnum
    {
        
        /// <summary>
        /// Enum PerNight for value: PerNight
        /// </summary>
        [EnumMember(Value = "PerNight")]
        PerNight = 1,
        
        /// <summary>
        /// Enum PerDay for value: PerDay
        /// </summary>
        [EnumMember(Value = "PerDay")]
        PerDay = 2,
        
        /// <summary>
        /// Enum PerStay for value: PerStay
        /// </summary>
        [EnumMember(Value = "PerStay")]
        PerStay = 3,
        
        /// <summary>
        /// Enum PerWeek for value: PerWeek
        /// </summary>
        [EnumMember(Value = "PerWeek")]
        PerWeek = 4,
        
        /// <summary>
        /// Enum RoundTrip for value: RoundTrip
        /// </summary>
        [EnumMember(Value = "RoundTrip")]
        RoundTrip = 5,
        
        /// <summary>
        /// Enum OneWay for value: OneWay
        /// </summary>
        [EnumMember(Value = "OneWay")]
        OneWay = 6
    }

}
