/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Location code
    /// </summary>
    [DataContract]
    public partial class FromTo :  IEquatable<FromTo>, IValidatableObject
    {
        /// <summary>
        /// Airport or City
        /// </summary>
        /// <value>Airport or City</value>
        [DataMember(Name="cityOrAirport", EmitDefaultValue=false)]
        public CityOrAirportEnum? CityOrAirport { get; set; }
        /// <summary>
        /// Initializes a new instance of the <see cref="FromTo" /> class.
        /// </summary>
        /// <param name="value">value.</param>
        /// <param name="cityOrAirport">Airport or City.</param>
        public FromTo(string value = default(string), CityOrAirportEnum? cityOrAirport = default(CityOrAirportEnum?))
        {
            this.Value = value;
            this.CityOrAirport = cityOrAirport;
        }
        
        /// <summary>
        /// Gets or Sets Value
        /// </summary>
        [DataMember(Name="value", EmitDefaultValue=false)]
        public string Value { get; set; }


        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FromTo {\n");
            sb.Append("  Value: ").Append(Value).Append("\n");
            sb.Append("  CityOrAirport: ").Append(CityOrAirport).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FromTo);
        }

        /// <summary>
        /// Returns true if FromTo instances are equal
        /// </summary>
        /// <param name="input">Instance of FromTo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FromTo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Value == input.Value ||
                    (this.Value != null &&
                    this.Value.Equals(input.Value))
                ) && 
                (
                    this.CityOrAirport == input.CityOrAirport ||
                    (this.CityOrAirport != null &&
                    this.CityOrAirport.Equals(input.CityOrAirport))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Value != null)
                    hashCode = hashCode * 59 + this.Value.GetHashCode();
                if (this.CityOrAirport != null)
                    hashCode = hashCode * 59 + this.CityOrAirport.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            // Value (string) maxLength
            if(this.Value != null && this.Value.Length > 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, length must be less than 3.", new [] { "Value" });
            }

            // Value (string) minLength
            if(this.Value != null && this.Value.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, length must be greater than 3.", new [] { "Value" });
            }

            // Value (string) pattern
            Regex regexValue = new Regex(@"([a-zA-Z]{3})", RegexOptions.CultureInvariant);
            if (false == regexValue.Match(this.Value).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Value, must match a pattern of " + regexValue, new [] { "Value" });
            }

            yield break;
        }
    }

}
