/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// FulfillmentMethod
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "@type")]
    public partial class FulfillmentMethod :  IEquatable<FulfillmentMethod>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethod" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected FulfillmentMethod() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="FulfillmentMethod" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="productRefs">The product(s) the Fulfillment Method applies to. If blank applies to all products in the Offer.</param>
        /// <param name="segmentSequenceList">Assigned Type: c-1100:SegmentSequenceList.</param>
        /// <param name="refundMethod">Assigned Type: ctar-1100:RefundMethodEnum.</param>
        /// <param name="changeFeeCollectionMethod">Assigned Type: ctar-1100:ChangeFeeCollectionMethod.</param>
        /// <param name="extensionPoint">extensionPoint.</param>
        public FulfillmentMethod(string type = default(string), List<string> productRefs = default(List<string>), List<int?> segmentSequenceList = default(List<int?>), RefundMethodEnum refundMethod = default(RefundMethodEnum), ChangeFeeCollectionMethod changeFeeCollectionMethod = default(ChangeFeeCollectionMethod), Object extensionPoint = default(Object))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for FulfillmentMethod and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            this.ProductRefs = productRefs;
            this.SegmentSequenceList = segmentSequenceList;
            this.RefundMethod = refundMethod;
            this.ChangeFeeCollectionMethod = changeFeeCollectionMethod;
            this.ExtensionPoint = extensionPoint;
        }
        
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="@type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// The product(s) the Fulfillment Method applies to. If blank applies to all products in the Offer
        /// </summary>
        /// <value>The product(s) the Fulfillment Method applies to. If blank applies to all products in the Offer</value>
        [DataMember(Name="productRefs", EmitDefaultValue=false)]
        public List<string> ProductRefs { get; set; }

        /// <summary>
        /// Assigned Type: c-1100:SegmentSequenceList
        /// </summary>
        /// <value>Assigned Type: c-1100:SegmentSequenceList</value>
        [DataMember(Name="segmentSequenceList", EmitDefaultValue=false)]
        public List<int?> SegmentSequenceList { get; set; }

        /// <summary>
        /// Assigned Type: ctar-1100:RefundMethodEnum
        /// </summary>
        /// <value>Assigned Type: ctar-1100:RefundMethodEnum</value>
        [DataMember(Name="RefundMethod", EmitDefaultValue=false)]
        public RefundMethodEnum RefundMethod { get; set; }

        /// <summary>
        /// Assigned Type: ctar-1100:ChangeFeeCollectionMethod
        /// </summary>
        /// <value>Assigned Type: ctar-1100:ChangeFeeCollectionMethod</value>
        [DataMember(Name="ChangeFeeCollectionMethod", EmitDefaultValue=false)]
        public ChangeFeeCollectionMethod ChangeFeeCollectionMethod { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPoint
        /// </summary>
        [DataMember(Name="ExtensionPoint", EmitDefaultValue=false)]
        public Object ExtensionPoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class FulfillmentMethod {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  ProductRefs: ").Append(ProductRefs).Append("\n");
            sb.Append("  SegmentSequenceList: ").Append(SegmentSequenceList).Append("\n");
            sb.Append("  RefundMethod: ").Append(RefundMethod).Append("\n");
            sb.Append("  ChangeFeeCollectionMethod: ").Append(ChangeFeeCollectionMethod).Append("\n");
            sb.Append("  ExtensionPoint: ").Append(ExtensionPoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as FulfillmentMethod);
        }

        /// <summary>
        /// Returns true if FulfillmentMethod instances are equal
        /// </summary>
        /// <param name="input">Instance of FulfillmentMethod to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(FulfillmentMethod input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.ProductRefs == input.ProductRefs ||
                    this.ProductRefs != null &&
                    this.ProductRefs.SequenceEqual(input.ProductRefs)
                ) && 
                (
                    this.SegmentSequenceList == input.SegmentSequenceList ||
                    this.SegmentSequenceList != null &&
                    this.SegmentSequenceList.SequenceEqual(input.SegmentSequenceList)
                ) && 
                (
                    this.RefundMethod == input.RefundMethod ||
                    (this.RefundMethod != null &&
                    this.RefundMethod.Equals(input.RefundMethod))
                ) && 
                (
                    this.ChangeFeeCollectionMethod == input.ChangeFeeCollectionMethod ||
                    (this.ChangeFeeCollectionMethod != null &&
                    this.ChangeFeeCollectionMethod.Equals(input.ChangeFeeCollectionMethod))
                ) && 
                (
                    this.ExtensionPoint == input.ExtensionPoint ||
                    (this.ExtensionPoint != null &&
                    this.ExtensionPoint.Equals(input.ExtensionPoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.ProductRefs != null)
                    hashCode = hashCode * 59 + this.ProductRefs.GetHashCode();
                if (this.SegmentSequenceList != null)
                    hashCode = hashCode * 59 + this.SegmentSequenceList.GetHashCode();
                if (this.RefundMethod != null)
                    hashCode = hashCode * 59 + this.RefundMethod.GetHashCode();
                if (this.ChangeFeeCollectionMethod != null)
                    hashCode = hashCode * 59 + this.ChangeFeeCollectionMethod.GetHashCode();
                if (this.ExtensionPoint != null)
                    hashCode = hashCode * 59 + this.ExtensionPoint.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
