/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines JourneyTypeEnum
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum JourneyTypeEnum
    {
        
        /// <summary>
        /// Enum OpenJaw for value: OpenJaw
        /// </summary>
        [EnumMember(Value = "OpenJaw")]
        OpenJaw = 1,
        
        /// <summary>
        /// Enum RoundTrip for value: RoundTrip
        /// </summary>
        [EnumMember(Value = "RoundTrip")]
        RoundTrip = 2,
        
        /// <summary>
        /// Enum CircleTrip for value: CircleTrip
        /// </summary>
        [EnumMember(Value = "CircleTrip")]
        CircleTrip = 3,
        
        /// <summary>
        /// Enum Outbound for value: Outbound
        /// </summary>
        [EnumMember(Value = "Outbound")]
        Outbound = 4,
        
        /// <summary>
        /// Enum Inbound for value: Inbound
        /// </summary>
        [EnumMember(Value = "Inbound")]
        Inbound = 5
    }

}
