/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using JsonSubTypes;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PassengerFlight
    /// </summary>
    [DataContract]
    [JsonConverter(typeof(JsonSubtypes), "@type")]
    public partial class PassengerFlight :  IEquatable<PassengerFlight>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PassengerFlight" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PassengerFlight() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PassengerFlight" /> class.
        /// </summary>
        /// <param name="type">type (required).</param>
        /// <param name="passengerQuantity">Number of passengers of the specified passenger type code.</param>
        /// <param name="passengerTypeCode">Assigned Type: c-1100:PassengerTypeCode.</param>
        /// <param name="flightProduct">flightProduct.</param>
        /// <param name="extensionPoint">extensionPoint.</param>
        public PassengerFlight(string type = default(string), int? passengerQuantity = default(int?), string passengerTypeCode = default(string), List<FlightProduct> flightProduct = default(List<FlightProduct>), Object extensionPoint = default(Object))
        {
            // to ensure "type" is required (not null)
            if (type == null)
            {
                throw new InvalidDataException("type is a required property for PassengerFlight and cannot be null");
            }
            else
            {
                this.Type = type;
            }
            this.PassengerQuantity = passengerQuantity;
            this.PassengerTypeCode = passengerTypeCode;
            this.FlightProduct = flightProduct;
            this.ExtensionPoint = extensionPoint;
        }
        
        /// <summary>
        /// Gets or Sets Type
        /// </summary>
        [DataMember(Name="@type", EmitDefaultValue=false)]
        public string Type { get; set; }

        /// <summary>
        /// Number of passengers of the specified passenger type code
        /// </summary>
        /// <value>Number of passengers of the specified passenger type code</value>
        [DataMember(Name="passengerQuantity", EmitDefaultValue=false)]
        public int? PassengerQuantity { get; set; }

        /// <summary>
        /// Assigned Type: c-1100:PassengerTypeCode
        /// </summary>
        /// <value>Assigned Type: c-1100:PassengerTypeCode</value>
        [DataMember(Name="passengerTypeCode", EmitDefaultValue=false)]
        public string PassengerTypeCode { get; set; }

        /// <summary>
        /// Gets or Sets FlightProduct
        /// </summary>
        [DataMember(Name="FlightProduct", EmitDefaultValue=false)]
        public List<FlightProduct> FlightProduct { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPoint
        /// </summary>
        [DataMember(Name="ExtensionPoint", EmitDefaultValue=false)]
        public Object ExtensionPoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PassengerFlight {\n");
            sb.Append("  Type: ").Append(Type).Append("\n");
            sb.Append("  PassengerQuantity: ").Append(PassengerQuantity).Append("\n");
            sb.Append("  PassengerTypeCode: ").Append(PassengerTypeCode).Append("\n");
            sb.Append("  FlightProduct: ").Append(FlightProduct).Append("\n");
            sb.Append("  ExtensionPoint: ").Append(ExtensionPoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PassengerFlight);
        }

        /// <summary>
        /// Returns true if PassengerFlight instances are equal
        /// </summary>
        /// <param name="input">Instance of PassengerFlight to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PassengerFlight input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Type == input.Type ||
                    (this.Type != null &&
                    this.Type.Equals(input.Type))
                ) && 
                (
                    this.PassengerQuantity == input.PassengerQuantity ||
                    (this.PassengerQuantity != null &&
                    this.PassengerQuantity.Equals(input.PassengerQuantity))
                ) && 
                (
                    this.PassengerTypeCode == input.PassengerTypeCode ||
                    (this.PassengerTypeCode != null &&
                    this.PassengerTypeCode.Equals(input.PassengerTypeCode))
                ) && 
                (
                    this.FlightProduct == input.FlightProduct ||
                    this.FlightProduct != null &&
                    this.FlightProduct.SequenceEqual(input.FlightProduct)
                ) && 
                (
                    this.ExtensionPoint == input.ExtensionPoint ||
                    (this.ExtensionPoint != null &&
                    this.ExtensionPoint.Equals(input.ExtensionPoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Type != null)
                    hashCode = hashCode * 59 + this.Type.GetHashCode();
                if (this.PassengerQuantity != null)
                    hashCode = hashCode * 59 + this.PassengerQuantity.GetHashCode();
                if (this.PassengerTypeCode != null)
                    hashCode = hashCode * 59 + this.PassengerTypeCode.GetHashCode();
                if (this.FlightProduct != null)
                    hashCode = hashCode * 59 + this.FlightProduct.GetHashCode();
                if (this.ExtensionPoint != null)
                    hashCode = hashCode * 59 + this.ExtensionPoint.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            return this.BaseValidate(validationContext);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        protected IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> BaseValidate(ValidationContext validationContext)
        {
            // PassengerTypeCode (string) maxLength
            if(this.PassengerTypeCode != null && this.PassengerTypeCode.Length > 5)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PassengerTypeCode, length must be less than 5.", new [] { "PassengerTypeCode" });
            }

            // PassengerTypeCode (string) minLength
            if(this.PassengerTypeCode != null && this.PassengerTypeCode.Length < 3)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PassengerTypeCode, length must be greater than 3.", new [] { "PassengerTypeCode" });
            }

            // PassengerTypeCode (string) pattern
            Regex regexPassengerTypeCode = new Regex(@"([a-zA-Z0-9]{3,5})", RegexOptions.CultureInvariant);
            if (false == regexPassengerTypeCode.Match(this.PassengerTypeCode).Success)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for PassengerTypeCode, must match a pattern of " + regexPassengerTypeCode, new [] { "PassengerTypeCode" });
            }

            yield break;
        }
    }

}
