/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PassengerCriteriaAirChange
    /// </summary>
    [DataContract]
    public partial class PassengerCriteriaAirChange : PassengerCriteria,  IEquatable<PassengerCriteriaAirChange>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PassengerCriteriaAirChange" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PassengerCriteriaAirChange() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PassengerCriteriaAirChange" /> class.
        /// </summary>
        /// <param name="travelerIdentifierRef">Assigned Type: c-1100:TravelerIdentifierRef (required).</param>
        /// <param name="extensionPointChoice">extensionPointChoice.</param>
        public PassengerCriteriaAirChange(TravelerIdentifierRef travelerIdentifierRef = default(TravelerIdentifierRef), ExtensionPointChoice extensionPointChoice = default(ExtensionPointChoice), string type = "PassengerCriteriaAirChange", int? number = default(int?), int? age = default(int?), string passengerTypeCode = default(string), List<CustomerLoyalty> customerLoyalty = default(List<CustomerLoyalty>), TravelerGeographicLocation travelerGeographicLocation = default(TravelerGeographicLocation), bool? specifiedPassengerTypeCodeOnlyInd = default(bool?), Object extensionPoint = default(Object)) : base(type, number, age, passengerTypeCode, customerLoyalty, travelerGeographicLocation, specifiedPassengerTypeCodeOnlyInd, extensionPoint)
        {
            // to ensure "travelerIdentifierRef" is required (not null)
            if (travelerIdentifierRef == null)
            {
                throw new InvalidDataException("travelerIdentifierRef is a required property for PassengerCriteriaAirChange and cannot be null");
            }
            else
            {
                this.TravelerIdentifierRef = travelerIdentifierRef;
            }
            this.ExtensionPointChoice = extensionPointChoice;
        }
        
        /// <summary>
        /// Assigned Type: c-1100:TravelerIdentifierRef
        /// </summary>
        /// <value>Assigned Type: c-1100:TravelerIdentifierRef</value>
        [DataMember(Name="TravelerIdentifierRef", EmitDefaultValue=false)]
        public TravelerIdentifierRef TravelerIdentifierRef { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointChoice
        /// </summary>
        [DataMember(Name="ExtensionPoint_Choice", EmitDefaultValue=false)]
        public ExtensionPointChoice ExtensionPointChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PassengerCriteriaAirChange {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  TravelerIdentifierRef: ").Append(TravelerIdentifierRef).Append("\n");
            sb.Append("  ExtensionPointChoice: ").Append(ExtensionPointChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PassengerCriteriaAirChange);
        }

        /// <summary>
        /// Returns true if PassengerCriteriaAirChange instances are equal
        /// </summary>
        /// <param name="input">Instance of PassengerCriteriaAirChange to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PassengerCriteriaAirChange input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.TravelerIdentifierRef == input.TravelerIdentifierRef ||
                    (this.TravelerIdentifierRef != null &&
                    this.TravelerIdentifierRef.Equals(input.TravelerIdentifierRef))
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointChoice == input.ExtensionPointChoice ||
                    (this.ExtensionPointChoice != null &&
                    this.ExtensionPointChoice.Equals(input.ExtensionPointChoice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.TravelerIdentifierRef != null)
                    hashCode = hashCode * 59 + this.TravelerIdentifierRef.GetHashCode();
                if (this.ExtensionPointChoice != null)
                    hashCode = hashCode * 59 + this.ExtensionPointChoice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
