/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PaymentAfterReservationDayOfWeek
    /// </summary>
    [DataContract]
    public partial class PaymentAfterReservationDayOfWeek : PaymentAfterReservation,  IEquatable<PaymentAfterReservationDayOfWeek>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentAfterReservationDayOfWeek" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PaymentAfterReservationDayOfWeek() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PaymentAfterReservationDayOfWeek" /> class.
        /// </summary>
        /// <param name="dayOfWeek">Assigned Type: c-1100:DayOfWeekEnum (required).</param>
        /// <param name="extensionPointChoice">extensionPointChoice.</param>
        public PaymentAfterReservationDayOfWeek(DayOfWeekEnum dayOfWeek = default(DayOfWeekEnum), ExtensionPointChoice extensionPointChoice = default(ExtensionPointChoice), string type = "PaymentAfterReservationDayOfWeek", string timeOfDay = default(string), Object extensionPoint = default(Object)) : base(type, timeOfDay, extensionPoint)
        {
            // to ensure "dayOfWeek" is required (not null)
            if (dayOfWeek == null)
            {
                throw new InvalidDataException("dayOfWeek is a required property for PaymentAfterReservationDayOfWeek and cannot be null");
            }
            else
            {
                this.DayOfWeek = dayOfWeek;
            }
            this.ExtensionPointChoice = extensionPointChoice;
        }
        
        /// <summary>
        /// Assigned Type: c-1100:DayOfWeekEnum
        /// </summary>
        /// <value>Assigned Type: c-1100:DayOfWeekEnum</value>
        [DataMember(Name="DayOfWeek", EmitDefaultValue=false)]
        public DayOfWeekEnum DayOfWeek { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointChoice
        /// </summary>
        [DataMember(Name="ExtensionPoint_Choice", EmitDefaultValue=false)]
        public ExtensionPointChoice ExtensionPointChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PaymentAfterReservationDayOfWeek {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  DayOfWeek: ").Append(DayOfWeek).Append("\n");
            sb.Append("  ExtensionPointChoice: ").Append(ExtensionPointChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PaymentAfterReservationDayOfWeek);
        }

        /// <summary>
        /// Returns true if PaymentAfterReservationDayOfWeek instances are equal
        /// </summary>
        /// <param name="input">Instance of PaymentAfterReservationDayOfWeek to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PaymentAfterReservationDayOfWeek input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.DayOfWeek == input.DayOfWeek ||
                    (this.DayOfWeek != null &&
                    this.DayOfWeek.Equals(input.DayOfWeek))
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointChoice == input.ExtensionPointChoice ||
                    (this.ExtensionPointChoice != null &&
                    this.ExtensionPointChoice.Equals(input.ExtensionPointChoice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.DayOfWeek != null)
                    hashCode = hashCode * 59 + this.DayOfWeek.GetHashCode();
                if (this.ExtensionPointChoice != null)
                    hashCode = hashCode * 59 + this.ExtensionPointChoice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
