/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// PricingModifiersAirDetail
    /// </summary>
    [DataContract]
    public partial class PricingModifiersAirDetail : PricingModifiersAir,  IEquatable<PricingModifiersAirDetail>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PricingModifiersAirDetail" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PricingModifiersAirDetail() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PricingModifiersAirDetail" /> class.
        /// </summary>
        /// <param name="brand">Assigned Type: ctbr-1100:Brand.</param>
        /// <param name="extensionPointDetail">extensionPointDetail.</param>
        public PricingModifiersAirDetail(BrandID brand = default(BrandID), ExtensionPointDetail extensionPointDetail = default(ExtensionPointDetail), string type = "PricingModifiersAirDetail", string currencyCode = default(string), FareSelection fareSelection = default(FareSelection), OrganizationInformation organizationInformation = default(OrganizationInformation), TaxExemption taxExemption = default(TaxExemption), List<PromotionalCode> promotionalCode = default(List<PromotionalCode>), string sellCity = default(string), string ticketCity = default(string), bool? includeSplitPaymentInd = default(bool?), Object extensionPoint = default(Object)) : base(type, currencyCode, fareSelection, organizationInformation, taxExemption, promotionalCode, sellCity, ticketCity, includeSplitPaymentInd, extensionPoint)
        {
            this.Brand = brand;
            this.ExtensionPointDetail = extensionPointDetail;
        }
        
        /// <summary>
        /// Assigned Type: ctbr-1100:Brand
        /// </summary>
        /// <value>Assigned Type: ctbr-1100:Brand</value>
        [DataMember(Name="Brand", EmitDefaultValue=false)]
        public BrandID Brand { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointDetail
        /// </summary>
        [DataMember(Name="ExtensionPoint_Detail", EmitDefaultValue=false)]
        public ExtensionPointDetail ExtensionPointDetail { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class PricingModifiersAirDetail {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Brand: ").Append(Brand).Append("\n");
            sb.Append("  ExtensionPointDetail: ").Append(ExtensionPointDetail).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PricingModifiersAirDetail);
        }

        /// <summary>
        /// Returns true if PricingModifiersAirDetail instances are equal
        /// </summary>
        /// <param name="input">Instance of PricingModifiersAirDetail to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PricingModifiersAirDetail input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Brand == input.Brand ||
                    (this.Brand != null &&
                    this.Brand.Equals(input.Brand))
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointDetail == input.ExtensionPointDetail ||
                    (this.ExtensionPointDetail != null &&
                    this.ExtensionPointDetail.Equals(input.ExtensionPointDetail))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Brand != null)
                    hashCode = hashCode * 59 + this.Brand.GetHashCode();
                if (this.ExtensionPointDetail != null)
                    hashCode = hashCode * 59 + this.ExtensionPointDetail.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
