/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// ProductOptionsSummary
    /// </summary>
    [DataContract]
    public partial class ProductOptionsSummary : ProductOptionsID,  IEquatable<ProductOptionsSummary>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductOptionsSummary" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected ProductOptionsSummary() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="ProductOptionsSummary" /> class.
        /// </summary>
        /// <param name="sequence">Assigned Type: c-1100:NonnegativeInteger.</param>
        /// <param name="product">product (required).</param>
        /// <param name="extensionPoint">extensionPoint.</param>
        public ProductOptionsSummary(int? sequence = default(int?), List<ProductID> product = default(List<ProductID>), Object extensionPoint = default(Object), string type = "ProductOptionsSummary", string id = default(string), Identifier identifier = default(Identifier), string productOptionsRef = default(string)) : base(type, id, identifier, productOptionsRef)
        {
            // to ensure "product" is required (not null)
            if (product == null)
            {
                throw new InvalidDataException("product is a required property for ProductOptionsSummary and cannot be null");
            }
            else
            {
                this.Product = product;
            }
            this.Sequence = sequence;
            this.ExtensionPoint = extensionPoint;
        }
        
        /// <summary>
        /// Assigned Type: c-1100:NonnegativeInteger
        /// </summary>
        /// <value>Assigned Type: c-1100:NonnegativeInteger</value>
        [DataMember(Name="sequence", EmitDefaultValue=false)]
        public int? Sequence { get; set; }

        /// <summary>
        /// Gets or Sets Product
        /// </summary>
        [DataMember(Name="Product", EmitDefaultValue=false)]
        public List<ProductID> Product { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPoint
        /// </summary>
        [DataMember(Name="ExtensionPoint", EmitDefaultValue=false)]
        public Object ExtensionPoint { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ProductOptionsSummary {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  Sequence: ").Append(Sequence).Append("\n");
            sb.Append("  Product: ").Append(Product).Append("\n");
            sb.Append("  ExtensionPoint: ").Append(ExtensionPoint).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as ProductOptionsSummary);
        }

        /// <summary>
        /// Returns true if ProductOptionsSummary instances are equal
        /// </summary>
        /// <param name="input">Instance of ProductOptionsSummary to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ProductOptionsSummary input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.Sequence == input.Sequence ||
                    (this.Sequence != null &&
                    this.Sequence.Equals(input.Sequence))
                ) && base.Equals(input) && 
                (
                    this.Product == input.Product ||
                    this.Product != null &&
                    this.Product.SequenceEqual(input.Product)
                ) && base.Equals(input) && 
                (
                    this.ExtensionPoint == input.ExtensionPoint ||
                    (this.ExtensionPoint != null &&
                    this.ExtensionPoint.Equals(input.ExtensionPoint))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.Sequence != null)
                    hashCode = hashCode * 59 + this.Sequence.GetHashCode();
                if (this.Product != null)
                    hashCode = hashCode * 59 + this.Product.GetHashCode();
                if (this.ExtensionPoint != null)
                    hashCode = hashCode * 59 + this.ExtensionPoint.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            // Sequence (int?) minimum
            if(this.Sequence < (int?)0)
            {
                yield return new System.ComponentModel.DataAnnotations.ValidationResult("Invalid value for Sequence, must be a value greater than or equal to 0.", new [] { "Sequence" });
            }

            yield break;
        }
    }

}
