/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// SeatAvailabilityOfferingsBuildFromCatalogOfferings
    /// </summary>
    [DataContract]
    public partial class SeatAvailabilityOfferingsBuildFromCatalogOfferings : SeatAvailabilityOfferings,  IEquatable<SeatAvailabilityOfferingsBuildFromCatalogOfferings>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="SeatAvailabilityOfferingsBuildFromCatalogOfferings" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected SeatAvailabilityOfferingsBuildFromCatalogOfferings() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="SeatAvailabilityOfferingsBuildFromCatalogOfferings" /> class.
        /// </summary>
        /// <param name="buildFromCatalogOfferingsRequest">Assigned Type: ctlg-1100:BuildFromCatalogOfferingsRequest (required).</param>
        /// <param name="extensionPointChoice">extensionPointChoice.</param>
        public SeatAvailabilityOfferingsBuildFromCatalogOfferings(BuildFromCatalogOfferingsRequest buildFromCatalogOfferingsRequest = default(BuildFromCatalogOfferingsRequest), ExtensionPointChoice extensionPointChoice = default(ExtensionPointChoice), string type = "SeatAvailabilityOfferingsBuildFromCatalogOfferings", Object extensionPoint = default(Object)) : base(type, extensionPoint)
        {
            // to ensure "buildFromCatalogOfferingsRequest" is required (not null)
            if (buildFromCatalogOfferingsRequest == null)
            {
                throw new InvalidDataException("buildFromCatalogOfferingsRequest is a required property for SeatAvailabilityOfferingsBuildFromCatalogOfferings and cannot be null");
            }
            else
            {
                this.BuildFromCatalogOfferingsRequest = buildFromCatalogOfferingsRequest;
            }
            this.ExtensionPointChoice = extensionPointChoice;
        }
        
        /// <summary>
        /// Assigned Type: ctlg-1100:BuildFromCatalogOfferingsRequest
        /// </summary>
        /// <value>Assigned Type: ctlg-1100:BuildFromCatalogOfferingsRequest</value>
        [DataMember(Name="BuildFromCatalogOfferingsRequest", EmitDefaultValue=false)]
        public BuildFromCatalogOfferingsRequest BuildFromCatalogOfferingsRequest { get; set; }

        /// <summary>
        /// Gets or Sets ExtensionPointChoice
        /// </summary>
        [DataMember(Name="ExtensionPoint_Choice", EmitDefaultValue=false)]
        public ExtensionPointChoice ExtensionPointChoice { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class SeatAvailabilityOfferingsBuildFromCatalogOfferings {\n");
            sb.Append("  ").Append(base.ToString().Replace("\n", "\n  ")).Append("\n");
            sb.Append("  BuildFromCatalogOfferingsRequest: ").Append(BuildFromCatalogOfferingsRequest).Append("\n");
            sb.Append("  ExtensionPointChoice: ").Append(ExtensionPointChoice).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public override string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as SeatAvailabilityOfferingsBuildFromCatalogOfferings);
        }

        /// <summary>
        /// Returns true if SeatAvailabilityOfferingsBuildFromCatalogOfferings instances are equal
        /// </summary>
        /// <param name="input">Instance of SeatAvailabilityOfferingsBuildFromCatalogOfferings to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(SeatAvailabilityOfferingsBuildFromCatalogOfferings input)
        {
            if (input == null)
                return false;

            return base.Equals(input) && 
                (
                    this.BuildFromCatalogOfferingsRequest == input.BuildFromCatalogOfferingsRequest ||
                    (this.BuildFromCatalogOfferingsRequest != null &&
                    this.BuildFromCatalogOfferingsRequest.Equals(input.BuildFromCatalogOfferingsRequest))
                ) && base.Equals(input) && 
                (
                    this.ExtensionPointChoice == input.ExtensionPointChoice ||
                    (this.ExtensionPointChoice != null &&
                    this.ExtensionPointChoice.Equals(input.ExtensionPointChoice))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = base.GetHashCode();
                if (this.BuildFromCatalogOfferingsRequest != null)
                    hashCode = hashCode * 59 + this.BuildFromCatalogOfferingsRequest.GetHashCode();
                if (this.ExtensionPointChoice != null)
                    hashCode = hashCode * 59 + this.ExtensionPointChoice.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            foreach(var x in BaseValidate(validationContext)) yield return x;
            yield break;
        }
    }

}
