/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Describes the format of text such as plain text or html
    /// </summary>
    /// <value>Describes the format of text such as plain text or html</value>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum TextFormatEnum
    {
        
        /// <summary>
        /// Enum PlainText for value: PlainText
        /// </summary>
        [EnumMember(Value = "PlainText")]
        PlainText = 1,
        
        /// <summary>
        /// Enum HTML for value: HTML
        /// </summary>
        [EnumMember(Value = "HTML")]
        HTML = 2
    }

}
