/* 
 * CatalogProductOfferingsResource
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 11.1.0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = IO.Swagger.Client.SwaggerDateConverter;

namespace IO.Swagger.Model
{
    /// <summary>
    /// Defines WaitlistStandbyConditionEnum_Base
    /// </summary>
    
    [JsonConverter(typeof(StringEnumConverter))]
    
    public enum WaitlistStandbyConditionEnumBase
    {
        
        /// <summary>
        /// Enum WaitlistStandbyNotPermitted for value: WaitlistStandbyNotPermitted
        /// </summary>
        [EnumMember(Value = "WaitlistStandbyNotPermitted")]
        WaitlistStandbyNotPermitted = 1,
        
        /// <summary>
        /// Enum WaitlistNotPermitted for value: WaitlistNotPermitted
        /// </summary>
        [EnumMember(Value = "WaitlistNotPermitted")]
        WaitlistNotPermitted = 2,
        
        /// <summary>
        /// Enum WaitlistStandbyNotPermittedOrigin for value: WaitlistStandbyNotPermittedOrigin
        /// </summary>
        [EnumMember(Value = "WaitlistStandbyNotPermittedOrigin")]
        WaitlistStandbyNotPermittedOrigin = 3,
        
        /// <summary>
        /// Enum StandbyNotPermittedOrigin for value: StandbyNotPermittedOrigin
        /// </summary>
        [EnumMember(Value = "StandbyNotPermittedOrigin")]
        StandbyNotPermittedOrigin = 4,
        
        /// <summary>
        /// Enum WaitlistNotPermittedOrigin for value: WaitlistNotPermittedOrigin
        /// </summary>
        [EnumMember(Value = "WaitlistNotPermittedOrigin")]
        WaitlistNotPermittedOrigin = 5,
        
        /// <summary>
        /// Enum WaitlistNotPermittedOnAny for value: WaitlistNotPermittedOnAny
        /// </summary>
        [EnumMember(Value = "WaitlistNotPermittedOnAny")]
        WaitlistNotPermittedOnAny = 6,
        
        /// <summary>
        /// Enum StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermitted for value: StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermitted
        /// </summary>
        [EnumMember(Value = "StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermitted")]
        StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermitted = 7,
        
        /// <summary>
        /// Enum StandbyPermittedEarlierLaterSameDayElseStandbyNotPermitted for value: StandbyPermittedEarlierLaterSameDayElseStandbyNotPermitted
        /// </summary>
        [EnumMember(Value = "StandbyPermittedEarlierLaterSameDayElseStandbyNotPermitted")]
        StandbyPermittedEarlierLaterSameDayElseStandbyNotPermitted = 8,
        
        /// <summary>
        /// Enum StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin for value: StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin
        /// </summary>
        [EnumMember(Value = "StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin")]
        StandbyPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin = 9,
        
        /// <summary>
        /// Enum WaitlistPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin for value: WaitlistPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin
        /// </summary>
        [EnumMember(Value = "WaitlistPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin")]
        WaitlistPermittedEarlierLaterSameDayElseWaitlistStandbyNotPermittedOrigin = 10,
        
        /// <summary>
        /// Enum StandbyPermittedSameDateOriginallyTicketedProvidedFlightTimeSpecificRulesMet for value: StandbyPermittedSameDateOriginallyTicketedProvidedFlightTimeSpecificRulesMet
        /// </summary>
        [EnumMember(Value = "StandbyPermittedSameDateOriginallyTicketedProvidedFlightTimeSpecificRulesMet")]
        StandbyPermittedSameDateOriginallyTicketedProvidedFlightTimeSpecificRulesMet = 11,
        
        /// <summary>
        /// Enum StandbyNotPermitted for value: StandbyNotPermitted
        /// </summary>
        [EnumMember(Value = "StandbyNotPermitted")]
        StandbyNotPermitted = 12,
        
        /// <summary>
        /// Enum Other for value: Other_
        /// </summary>
        [EnumMember(Value = "Other_")]
        Other = 13
    }

}
